# Generated by Django 3.2.6 on 2021-09-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='account',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='zip_code',
        ),
    ]
