# Generated by Django 3.2.6 on 2021-09-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210919_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address1',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='ZIP / Postal code'),
        ),
    ]
