# Generated by Django 3.2.6 on 2021-09-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image_data',
            field=models.ManyToManyField(related_name='products', to='product.Image'),
        ),
    ]
