# Generated by Django 3.2.6 on 2021-09-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_imagemodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ('-date_added',), 'verbose_name': 'ImageModel', 'verbose_name_plural': 'ImageModels'},
        ),
    ]
